name: Update Google Scholar badges

on:
  schedule:
    # Runs daily at 06:00 UTC (adjust cron if you want a different time)
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f google_scholar_crawler/requirements.txt ]; then pip install -r google_scholar_crawler/requirements.txt; fi

      - name: Run Google Scholar crawler
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          # prefer explicit id from secret; script also supports other sources
          python3 google_scholar_crawler/main.py -i "${GOOGLE_SCHOLAR_ID}"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Only stage the generated badge/data files to avoid committing unrelated changes
          git add results/gs_data.json results/gs_data_shieldsio.json || true
          git add google_scholar_crawler/gs_data.json google_scholar_crawler/gs_data_shieldsio.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update Google Scholar badges and data"
            git push
          fi