name: Update Google Scholar badges

on:
  schedule:
    # Runs daily at 06:00 UTC (adjust cron if you want a different time)
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f google_scholar_crawler/requirements.txt ]; then pip install -r google_scholar_crawler/requirements.txt; fi

      - name: Debug repo contents (temporary)
        run: |
          echo "--- Debug: current working directory ---"
          pwd
          echo "--- Debug: list top-level files ---"
          ls -la
          echo "--- Debug: list google_scholar_crawler/ ---"
          ls -la google_scholar_crawler || true
          echo "--- Debug: show gs_id.txt if present ---"
          if [ -f google_scholar_crawler/gs_id.txt ]; then
            echo "gs_id.txt found:"; cat google_scholar_crawler/gs_id.txt
          else
            echo "gs_id.txt not found"
          fi

      - name: Run Google Scholar crawler
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          # prefer explicit id from secret; fallback to google_scholar_crawler/gs_id.txt if present
          if [ -n "${GOOGLE_SCHOLAR_ID}" ]; then
            ID="${GOOGLE_SCHOLAR_ID}"
          elif [ -f google_scholar_crawler/gs_id.txt ]; then
            ID=$(cat google_scholar_crawler/gs_id.txt | tr -d '\n' )
          else
            echo "No Google Scholar ID provided via secret or gs_id.txt — skipping run."
            exit 0
          fi
          echo "Using Google Scholar ID: ${ID}"
          python3 google_scholar_crawler/main.py -i "${ID}"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Only stage the generated badge/data files to avoid committing unrelated changes
          git add results/gs_data.json results/gs_data_shieldsio.json || true
          git add google_scholar_crawler/gs_data.json google_scholar_crawler/gs_data_shieldsio.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update Google Scholar badges and data"
            git push
          fi